
package Forms;

import DAO.DietaDAO;
import DAO.PlanAlimentacionDAO;
import Entities.DietaCliente;
import Entities.PlanAlimentacion;
import Controller.CargarDatosDieta;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormDieta extends javax.swing.JFrame {

    private final CargarDatosDieta controlador;
    private final PlanAlimentacionDAO planDAO;
    
    public FormDieta() {
        initComponents();
        controlador = new CargarDatosDieta();
        planDAO = new PlanAlimentacionDAO();
        txtiddieta.setEditable(false);
        
        // Inicializar ComboBox
        cmbnombre.removeAllItems();
        cmbnombre.addItem("Desayuno");
        cmbnombre.addItem("Almuerzo");
        cmbnombre.addItem("Cena");

        cargarComboPlanes();
        cargarTablaDietas();
        tabladieta.setDefaultEditor(Object.class, null);
        tabladieta.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnvolver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtiddieta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbnombre = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtingrediente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        btnlimpiarcampos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbplanalimentacion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladieta = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnvolver.setText("VOLVER");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre:");

        cmbnombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Ingrediente:");

        jLabel4.setText("Cantidad:");

        btnlimpiarcampos.setText("LIMPIAR CAMPOS");
        btnlimpiarcampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarcamposActionPerformed(evt);
            }
        });

        jLabel5.setText("Plan Alimentacion:");

        cmbplanalimentacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtiddieta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbplanalimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(3, 3, 3)
                        .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnlimpiarcampos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtiddieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(cmbnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbplanalimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnlimpiarcampos))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        tabladieta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Plan Alimentación", "Nombre", "Ingrediente", "Cantidad"
            }
        ));
        tabladieta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladietaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabladieta);

        btnagregar.setText("AGREGAR");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnmodificar.setText("MODIFICAR");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnvolver)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnagregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnvolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnagregar)
                        .addGap(83, 83, 83)
                        .addComponent(btnmodificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(btneliminar)
                        .addGap(63, 63, 63))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void cargarComboPlanes() {
    cmbplanalimentacion.removeAllItems();
    List<PlanAlimentacion> planes = planDAO.listarTodos();
    for (PlanAlimentacion p : planes) {
        cmbplanalimentacion.addItem(p.getNombre()); // solo nombres
    }
        cmbplanalimentacion.setSelectedIndex(-1); // nada seleccionado por defecto
    }
    
    private void cargarTablaDietas() {
        controlador.cargarTabla(tabladieta);
    }
    
    private void limpiarCampos() {
        txtiddieta.setText("");
        cmbnombre.setSelectedIndex(0);
        cmbplanalimentacion.setSelectedIndex(-1);
        txtingrediente.setText("");
        txtcantidad.setText("");
    }
    
    private void tablaClick() {
        int fila = tabladieta.getSelectedRow();
        if (fila >= 0) {
            txtiddieta.setText(tabladieta.getValueAt(fila, 0).toString());
            txtingrediente.setText(tabladieta.getValueAt(fila, 3).toString());
            txtcantidad.setText(tabladieta.getValueAt(fila, 4).toString());
        }
    }
    
    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        Forms.FormPlanAlimentacion panelPlan = new Forms.FormPlanAlimentacion();
        panelPlan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
              
        try {
            
            // Validación de combobox
            if (cmbplanalimentacion.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione un plan de alimentación.");
                return;
            }
            if (cmbnombre.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione un nombre de dieta (Desayuno, Almuerzo, Cena).");
                return;
            }
            
            String nombrePlan = (String) cmbplanalimentacion.getSelectedItem();
            if (nombrePlan == null) {
                JOptionPane.showMessageDialog(this, "Seleccione un plan de alimentación.");
                return;
            }
            PlanAlimentacion plan = planDAO.buscarPorNombre(nombrePlan);

            DietaCliente dieta = new DietaCliente();
            dieta.setNombre(cmbnombre.getSelectedItem().toString());
            dieta.setIngrediente(txtingrediente.getText().trim());
            dieta.setCantidad(txtcantidad.getText().trim());
            dieta.setPlan(plan);

            if (controlador.guardarDieta(dieta)) {
                JOptionPane.showMessageDialog(this, "Dieta agregada correctamente.");
                cargarTablaDietas();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Datos inválidos.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
       
       try {
           
           // Validación de combobox
            if (cmbplanalimentacion.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione un plan de alimentación.");
                return;
            }
            if (cmbnombre.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione un nombre de dieta (Desayuno, Almuerzo, Cena).");
                return;
            }
           
            int id = Integer.parseInt(txtiddieta.getText());
            DietaCliente dieta = controlador.obtenerPorId(id);
            if (dieta == null) return;

            String nombrePlan = (String) cmbplanalimentacion.getSelectedItem();
            PlanAlimentacion plan = planDAO.buscarPorNombre(nombrePlan);

            dieta.setNombre(cmbnombre.getSelectedItem().toString());
            dieta.setIngrediente(txtingrediente.getText().trim());
            dieta.setCantidad(txtcantidad.getText().trim());
            dieta.setPlan(plan);

            if (controlador.actualizarDieta(dieta)) {
                JOptionPane.showMessageDialog(this, "Dieta modificada correctamente.");
                cargarTablaDietas();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Datos inválidos.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Seleccione una dieta de la tabla.");
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        try {
            int id = Integer.parseInt(txtiddieta.getText());
            controlador.eliminarDieta(id);
            JOptionPane.showMessageDialog(this, "Dieta eliminada correctamente.");
            cargarTablaDietas();
            limpiarCampos();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Seleccione una dieta de la tabla.");
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnlimpiarcamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarcamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnlimpiarcamposActionPerformed

    private void tabladietaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladietaMouseClicked
        tablaClick();
    }//GEN-LAST:event_tabladietaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDieta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlimpiarcampos;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JComboBox<String> cmbnombre;
    private javax.swing.JComboBox<String> cmbplanalimentacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladieta;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtiddieta;
    private javax.swing.JTextField txtingrediente;
    // End of variables declaration//GEN-END:variables
}
